# Generated by Django 4.0.4 on 2022-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
