# Generated by Django 4.0.4 on 2022-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rand',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
